services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4 # 최신 버전으로 변경
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false # Trial 버전 테스트를 위해 보안 기능 비활성화 (선택 사항)
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 메모리 설정 (필요에 따라 조절)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data # 데이터 영속성 유지
    ports:
      - 19200:9200
      - 19300:9300
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4 # 최신 버전으로 변경
    container_name: kibana
    ports:
      - 15601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:

networks:
  elastic:
    driver: bridge