OPENAI_API_KEY = ""
CLAUDE_API_KEY = ""
GEMINI_API_KEY = ""
UNSTRUCTURED_API_KEY = ""

POSTGRES_CONNECTION_STRING = "postgresql+psycopg://postgres:{mypw}@localhost:5432/streamlit_documents"
POSTGRES_COLLECTION_NAME = "my_rag_documents"

OPENSEARCH_CONNECTION_STRING = "https://localhost:9200"
OPENSEARCH_USERNAME = "admin"
OPENSEARCH_PASSWORD = ""
OPENSEARCH_INDEX_NAME = "streamlit_documents"
OPENSEARCH_CACHE_INDEX_NAME = "embedding_cache"

ELASTICSEARCH_CONNECTION_STRING = "http://localhost:19200"
ELASTICSEARCH_USERNAME = "elastic"
ELASTICSEARCH_PASSWORD = ""
ELASTICSEARCH_INDEX_NAME = "streamlit_documents"
ELASTICSEARCH_CACHE_INDEX_NAME = "embedding_cache"
