OPENAI_API_KEY = ""
UNSTRUCTURED_API_KEY = ""

OPENSEARCH_HOST = "localhost"
OPENSEARCH_PORT = 9200
OPENSEARCH_USERNAME = "admin"
OPENSEARCH_PASSWORD = ""
OPENSEARCH_INDEX_NAME = "streamlit_documents"
OPENSEARCH_CACHE_INDEX_NAME = "embedding_cache"

ELASTICSEARCH_SCHEME = "http"
ELASTICSEARCH_HOST = "localhost"
ELASTICSEARCH_PORT = 19200 # 9243 for HTTPS
ELASTICSEARCH_USERNAME = "elastic"
ELASTICSEARCH_PASSWORD = ""
ELASTICSEARCH_INDEX_NAME = "streamlit_documents"
ELASTICSEARCH_CACHE_INDEX_NAME = "embedding_cache"
