OPENAI_API_KEY = ""
GEMINI_API_KEY = ""
UNSTRUCTURED_API_KEY = ""

POSTGRES_CONNECTION_STRING = "postgresql+psycopg://postgres:{mypw}@localhost:5432/streamlit_documents"
POSTGRES_COLLECTION_NAME = "my_rag_documents"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = ""
POSTGRES_DBNAME = "streamlit_documents"

OPENSEARCH_HOST = "localhost"
OPENSEARCH_PORT = 9200
OPENSEARCH_USERNAME = "admin"
OPENSEARCH_PASSWORD = ""
OPENSEARCH_INDEX_NAME = "streamlit_documents"
OPENSEARCH_CACHE_INDEX_NAME = "embedding_cache"

ELASTICSEARCH_SCHEME = "http"
ELASTICSEARCH_HOST = "localhost"
ELASTICSEARCH_PORT = 19200 # 9243 for HTTPS
ELASTICSEARCH_USERNAME = "elastic"
ELASTICSEARCH_PASSWORD = ""
ELASTICSEARCH_INDEX_NAME = "streamlit_documents"
ELASTICSEARCH_CACHE_INDEX_NAME = "embedding_cache"
